/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iEFsVwgtbKB
 */
import Link from "next/link"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col min-h-screen bg-blue-900">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <span className="text-lg font-bold text-white">Eirik Breen</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <a className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#projects">
            Projects
          </a>
          <a className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#skills">
            Skills
          </a>
          <a className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#experience">
            Experience
          </a>
          <a className="text-sm font-medium hover:underline underline-offset-4 text-white" href="#contact">
            Contact
          </a>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-6 sm:py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl text-white">
                    Hello, I&apos;m Eirik Breen
                  </h1>
                  <p className="max-w-[600px] text-gray-200 md:text-xl dark:text-gray-400">
                    A professional web developer with a passion for creating unique and innovative web experiences.
                  </p>
                </div>
                <a
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Contact Me
                </a>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-blue-800" id="projects">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <a href="#projects">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-white">My Projects</h2>
                </a>
                <p className="max-w-[900px] text-gray-200 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Here are some of my recent projects. Click on them to learn more.
                </p>
              </div>
            </div>
            <div className="grid gap-6 lg:gap-12 xl:gap-16 mt-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
              <Card className="rounded-lg overflow-hidden shadow-lg">
                <CardHeader>
                  <img
                    alt="Project Image"
                    className="object-cover w-full h-48"
                    height="200"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "300/200",
                      objectFit: "cover",
                    }}
                    width="300"
                  />
                </CardHeader>
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-white">Project Name 1</h3>
                  <p className="text-gray-200 dark:text-gray-400">Short description of project 1.</p>
                </CardContent>
              </Card>
              <Card className="rounded-lg overflow-hidden shadow-lg">
                <CardHeader>
                  <img
                    alt="Project Image"
                    className="object-cover w-full h-48"
                    height="200"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "300/200",
                      objectFit: "cover",
                    }}
                    width="300"
                  />
                </CardHeader>
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-white">Project Name 2</h3>
                  <p className="text-gray-200 dark:text-gray-400">Short description of project 2.</p>
                </CardContent>
              </Card>
              <Card className="rounded-lg overflow-hidden shadow-lg">
                <CardHeader>
                  <img
                    alt="Project Image"
                    className="object-cover w-full h-48"
                    height="200"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "300/200",
                      objectFit: "cover",
                    }}
                    width="300"
                  />
                </CardHeader>
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-white">Project Name 3</h3>
                  <p className="text-gray-200 dark:text-gray-400">Short description of project 3.</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="skills">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <a href="#Skills">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-white">My Skills</h2>
                </a>
                <p className="max-w-[900px] text-gray-200 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  I have a wide array of skills ranging from front-end development to back-end development.
                </p>
              </div>
            </div>
            <div className="flex flex-wrap justify-center mt-8 space-x-4">
              <Badge className="my-2" variant="secondary">
                JavaScript
              </Badge>
              <Badge className="my-2" variant="secondary">
                TypeScript
              </Badge>
              <Badge className="my-2" variant="secondary">
                React
              </Badge>
              <Badge className="my-2" variant="secondary">
                Node.js
              </Badge>
              <Badge className="my-2" variant="secondary">
                Express
              </Badge>
              <Badge className="my-2" variant="secondary">
                MongoDB
              </Badge>
              <Badge className="my-2" variant="secondary">
                PostgreSQL
              </Badge>
              <Badge className="my-2" variant="secondary">
                CSS
              </Badge>
              <Badge className="my-2" variant="secondary">
                HTML
              </Badge>
              <Badge className="my-2" variant="secondary">
                Git
              </Badge>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-blue-800" id="experience">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <a href="#experience">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-white">Experience</h2>
                </a>
                <p className="max-w-[900px] text-gray-200 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  I have worked with a number of companies and have gained a lot of experience over the years.
                </p>
              </div>
            </div>
            <div className="grid gap-6 lg:gap-12 xl:gap-16 mt-8 grid-cols-1 sm:grid-cols-2">
              <Card className="rounded-lg overflow-hidden shadow-lg">
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-white">Company Name 1</h3>
                  <p className="text-gray-200 dark:text-gray-400">
                    Short description of work experience at Company Name 1.
                  </p>
                </CardContent>
              </Card>
              <Card className="rounded-lg overflow-hidden shadow-lg">
                <CardContent className="p-4">
                  <h3 className="text-xl font-bold text-white">Company Name 2</h3>
                  <p className="text-gray-200 dark:text-gray-400">
                    Short description of work experience at Company Name 2.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="contact">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <a href="#contact">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-white">Contact Me</h2>
                </a>
                <p className="max-w-[900px] text-gray-200 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Feel free to reach out if you&apos;re looking for a developer, have a question, or just want to connect.
                </p>
              </div>
            </div>
            <div className="mt-8 flex justify-center">
              <Button className="mx-2" variant="secondary">
                <a href="#">Email me</a>
              </Button>
              <Button className="mx-2" variant="secondary">
                <a href="#" rel="noopener noreferrer" target="_blank">
                  GitHub
                </a>
              </Button>
              <Button className="mx-2" variant="secondary">
                <a href="#" rel="noopener noreferrer" target="_blank">
                  LinkedIn
                </a>
              </Button>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-gray-800">
        <p className="text-xs text-gray-200 dark:text-gray-400">© Eirik Breen. All rights reserved.</p>
      </footer>
    </div>
  )
}
